const assert=require('node:assert/strict'),fs=require('node:fs');const {DungeonExplorer}=require('./game-engine'),{takeWeaponAt}=require('./test-loot-helpers');const read=p=>JSON.parse(fs.readFileSync(p));const map=read('dungeon_map.json'),rules=read('game_rules.json'),bestiary=read('bestiary.json'),loot=read('loot.json');const make=cls=>new DungeonExplorer(map,rules,cls,'Test',{bestiary,loot,random:()=>.99});
for(const cls of ['Fighter','Rogue','Mage']){const g=make(cls);for(const room of map.rooms){g.roomId=room.id;for(const e of g.roomLoot){assert.ok(g.walkable(e.position));assert.ok(!g.currentEnemies.some(m=>g.distance(e.position,m.position)===0));}}
 g.roomId='hall';const e=g.roomLoot[0];g.position={x:999,y:999};assert.equal(g.takeLoot(e.uid),false);assert.equal(g.inventory.shadow_cloak,undefined);g.position={x:e.position.x+1,y:e.position.y};assert.ok(g.takeLoot(e.uid));assert.equal(g.inventory.shadow_cloak,1);assert.equal(g.roomLoot.length,0);assert.equal(g.takeLoot(e.uid),false);
 for(const id of ['rune_staff','lightning_staff','ice_staff','fireball_staff']){g.roomId='armory';assert.ok(takeWeaponAt(g,id));assert.equal(Object.keys(g.inventory).filter(k=>g.items.get(k).slot==='weapon').length,1);if(cls!=='Mage'){assert.equal(g.attackSpec.dice,'1d4');assert.equal(g.attackCost,1);assert.equal(g.attackSpec.effect,undefined);assert.equal(g.weaponBonus,0);}else assert.equal(g.attackSpec.stat,'INT');}
}
const drop=make('Fighter');drop.roomId='armory';const original=drop.equipment.weapon;assert.ok(takeWeaponAt(drop,'lightning_staff'));const position={...drop.position};const dropped=drop.roomLoot.find(e=>e.id===original);assert.deepEqual(dropped.position,position);drop.roomId='hall';drop.roomId='armory';drop.position={...position};assert.ok(drop.takeWeapon(original,dropped.uid));assert.equal(drop.equipment.weapon,original);assert.ok(drop.roomLoot.some(e=>e.id==='lightning_staff'));assert.ok(!drop.roomLoot.some(e=>e.uid===dropped.uid));
function combatWith(id,cls='Mage'){const g=make(cls);g.roomId='armory';assert.ok(takeWeaponAt(g,id));g.roomId='barracks';g.position=g.spawnPosition();g.engage();g.combat.phase='player';g.target.hp=g.target.maxHp=100;return g;}
const lightning=combatWith('lightning_staff');lightning.target.definition={...lightning.target.definition,defense:15};const hitDie=15-lightning.mod('INT')-2;lightning.random=()=> (hitDie-.5)/20;lightning.attack();assert.ok(lightning.target.hp<100,'Şimşek 2 AC delmeli');assert.equal(lightning.combat.ap,2);
const ice=combatWith('ice_staff');ice.attack();assert.ok(ice.target.chilled);ice.endTurn();const enemy=ice.target,die=ice.ac+1-enemy.definition.attack_bonus;ice.random=()=> (die-.5)/20;const hp=ice.hp;ice.enemyTurn();assert.equal(ice.hp,hp,'Buzun -2 isabeti bu saldırıyı engellemeli');assert.equal(enemy.chilled,false);
const fire=combatWith('fireball_staff');fire.attack();assert.equal(fire.combat.ap,1);assert.equal(fire.target.burning,2);const burned=fire.target;burned.hp=2;fire.endTurn();fire.enemyTurn();assert.equal(burned.hp,0);assert.equal(fire.combat,null);assert.ok(!fire.currentEnemies.length);
const fighter=combatWith('fireball_staff','Fighter');fighter.attack();assert.equal(fighter.target.hp,93);assert.equal(fighter.target.burning,undefined);assert.equal(fighter.combat.ap,2);
console.log('Passed: per-item nearby-only loot, valid blue-map positions, no duplicate pickup, dropped-weapon block persistence, all-class staff use, Mage lightning/frost/fire effects, physical staff damage and AP.');
