const {collectRoom,takeWeaponAt,winCombat}=require('./test-loot-helpers');
const assert=require('node:assert/strict'),fs=require('node:fs');const {DungeonExplorer}=require('./game-engine');const read=p=>JSON.parse(fs.readFileSync(p));const map=read('dungeon_map.json'),rules=read('game_rules.json'),bestiary=read('bestiary.json'),loot=read('loot.json');const make=cls=>new DungeonExplorer(map,rules,cls,'Kaşif',{bestiary,loot,random:()=>.99});
assert.equal(map.riddles.length,4);assert.equal(new Set(map.rooms.map(r=>r.art)).size,map.rooms.length);assert.equal(map.rooms.flatMap(r=>r.readings).length,26);for(const room of map.rooms){assert.ok(room.description.length>100);assert.ok(room.inspection.length>100);for(const item of room.loot)assert.ok(loot.items.some(i=>i.id===item.id));}assert.equal(map.rooms.filter(r=>r.loot.some(i=>i.id==='seal_stone')).length,1);
for(const cls of ['Fighter','Mage','Rogue']){const g=make(cls);function visit(target){if(g.currentEnemies.length&&!g.bypassed)g.sneak();assert.equal(g.combat,null);const d=g.doors().find(d=>d.target===target);assert.ok(d);g.position=g.spawnPosition(d);assert.equal(g.goDoor(d.id),true);assert.equal(g.roomId,target);winCombat(g);assert.equal(g.combat,null);}
g.prepare();visit('hall');collectRoom(g);g.useItem('shadow_cloak');visit('troll_hall');g.inspect();assert.ok(g.readEntry('text_0'));g.sneak();assert.ok(g.bypassed);assert.equal(g.currentEnemies[0].hp,65);visit('seal_room');g.answerRiddle(g.riddle.answer);g.rest();visit('guardian');g.sneak();visit('vault');assert.equal(g.hasStone,false);collectRoom(g);assert.equal(g.hasStone,true);visit('guardian');visit('seal_room');visit('troll_hall');visit('hall');visit('entrance');assert.ok(g.completed);assert.ok(!g.dead);}
const gear=make('Fighter');gear.roomId='armory';collectRoom(gear);takeWeaponAt(gear,'ash_cleaver');assert.equal(gear.weaponBonus,4);const ac=gear.ac;gear.useItem('warded_armor');assert.equal(gear.ac,ac+2);gear.useItem('warded_armor');assert.equal(gear.ac,ac+2);const count=gear.inventory.fury_potion;collectRoom(gear);assert.equal(gear.inventory.fury_potion,count);gear.roomId='barracks';gear.engage();gear.combat.phase='player';gear.target.hp=200;gear.useItem('fury_potion');assert.equal(gear.combat.ap,2);gear.attack();gear.attack();assert.equal(gear.damageBuff,null);assert.equal(gear.combat.phase,'enemy');
const rogue=make('Rogue');rogue.roomId='armory';collectRoom(rogue);const stealth=rogue.stealth;takeWeaponAt(rogue,'whisper_dagger');assert.equal(rogue.stealth,stealth+1);assert.equal(rogue.weaponBonus,3);
const mage=make('Mage');mage.roomId='armory';collectRoom(mage);takeWeaponAt(mage,'rune_staff');assert.equal(mage.weaponBonus,2);mage.useItem('ash_cleaver');assert.equal(mage.equipment.weapon,'rune_staff');
console.log('Passed: all three classes complete actual direct-door/stealth/riddle/objective return routes; unique room art, 26 readings, equipment compatibility, loot once and one-turn damage.');
