const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {DungeonExplorer}=require('./game-engine');const read=p=>JSON.parse(fs.readFileSync(p));const map=read('dungeon_map.json'),rules=read('game_rules.json'),bestiary=read('bestiary.json'),loot=read('loot.json');
const make=(cls='Fighter',random=()=>.5,extra={})=>new DungeonExplorer(map,rules,cls,'Test',{bestiary,loot,random,...extra});
const g=make();assert.equal(g.room.name,'Zindan Hücreleri');assert.equal(g.hp,30);assert.equal(g.potions,0);assert.equal(typeof g.move,'function');g.inspect();assert.ok(g.inspected.has(map.start));assert.ok(g.readEntry('text_0').text.length>100);g.hp=10;g.interact('water');assert.equal(g.hp,14);g.interact('water');assert.equal(g.hp,14);
const door=g.doors()[0];g.position=g.spawnPosition(door);assert.ok(g.goDoor(door.id));assert.equal(typeof g.advanceCorridor,'undefined');assert.equal(g.canAct(),true);assert.equal(g.roomId,'hall');assert.equal(g.combat,null);
g.roomId='barracks';g.bypassed=false;assert.equal(g.goDoor(g.doors()[0].id),false);g.prepare();assert.equal(g.combat,null);g.engage();assert.ok(g.combat);assert.equal(g.combat.preparedAtStart,true);g.combat.phase='player';g.target.hp=100;g.target.maxHp=100;g.attack();g.attack();g.attack();assert.equal(g.combat.phase,'enemy');g.enemyTurn();assert.equal(g.combat.ap,3);assert.ok(g.hp<g.maxHp);
function sneakRate(cls){let wins=0;for(let die=1;die<=20;die++){const x=make(cls);x.roomId='barracks';x.random=()=> (die-.5)/20;x.sneak();if(x.bypassed)wins++;}return wins;}
assert.equal(sneakRate('Fighter'),3);assert.equal(sneakRate('Rogue'),18);
for(let i=0;i<4;i++){const x=make('Rogue',()=> (i+.1)/4);assert.equal(x.riddle.id,map.riddles[i].id);x.roomId='seal_room';assert.equal(x.answerRiddle((x.riddle.answer+1)%4),false);assert.equal(x.sealSolved,false);assert.ok(x.alarm>0);assert.equal(x.answerRiddle(x.riddle.answer),true);assert.equal(x.sealSolved,true);}
const previous=make().riddle.id;assert.notEqual(make('Fighter',()=>.5,{previousRiddleId:previous}).riddle.id,previous);
const mage=make('Mage',()=>.9);mage.roomId='rune_hall';mage.inspect();mage.interact('brew');assert.equal(mage.potions,1);mage.interact('brew');assert.equal(mage.potions,1);mage.position=mage.spawnPosition(mage.doors().find(d=>d.target==='archive'));mage.goDoor(mage.doors().find(d=>d.target==='archive').id);assert.equal(mage.focus,5);mage.inspect();assert.ok(mage.finalAdvantage);mage.focus=4;mage.interact('study');assert.equal(mage.focus,6);
const elements=new Map(),timers=new Map();let id=0;
function classes(){const values=new Set();return {add(v){values.add(v);},remove(v){values.delete(v);},toggle(v,on){if(on)values.add(v);else values.delete(v);},contains(v){return values.has(v);}};}
function el(name){if(!elements.has(name))elements.set(name,{textContent:'',innerHTML:'',value:'',hidden:false,disabled:false,open:false,style:{},classList:classes(),attributes:{},listeners:{},setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,v){this.listeners[k]=v;},querySelectorAll(){return [];},showModal(){this.open=true;},close(){this.open=false;},setCustomValidity(){},reportValidity(){}});return elements.get(name);}
const storage=new Map();const context={CHARACTER_NAMES:require('./character-name-data'),MAP:map,RULES:rules,BESTIARY:bestiary,LOOT:loot,ASSETS:Object.fromEntries([...map.rooms.map(r=>r.art),...map.rooms.map(r=>r.enemy_art).filter(Boolean),'simple_vault_empty'].map(k=>[k,'test:'+k])),document:{body:{classList:classes()},getElementById:el,querySelectorAll(){return [];}},localStorage:{getItem(k){return storage.get(k)||null;},setItem(k,v){storage.set(k,v);}},setTimeout(fn){timers.set(++id,fn);return id;},clearTimeout(key){timers.delete(key);}};vm.createContext(context);vm.runInContext(fs.readFileSync('game-engine.js','utf8'),context);vm.runInContext(fs.readFileSync('game-ui.js','utf8'),context);
assert.ok(el('characterDialog').open);const generatedName=el('nameInput').value;assert.ok(generatedName.length>0&&generatedName.length<=36);assert.match(el('nameSuggestions').innerHTML,/data-suggested-name/);el('rerollName').listeners.click();assert.notEqual(el('nameInput').value,generatedName);el('nameInput').value='Mira';el('classInput').value='Rogue';el('characterForm').listeners.submit({preventDefault(){}});assert.ok(el('questDialog').open);el('acceptQuest').listeners.click();assert.match(el('scene').innerHTML,/data-background="simple_prison"/);assert.ok(!el('explorationActions').innerHTML.includes('adım'));assert.ok(el('doorChoices').hidden);assert.match(el('miniControls').innerHTML,/3 adım/);assert.match(el('miniGrid').innerHTML,/map-cell/);context.action('inspect');assert.equal(el('roomDetails').hidden,false);assert.ok(el('roomDetailsDialog').open);el('roomDetailsDialog').close();assert.match(el('roomReadings').innerHTML,/tutsağın/);
vm.runInContext("game.position=game.spawnPosition(game.doors()[0]);game.goDoor(game.doors()[0].id);render();",context);assert.match(el('scene').innerHTML,/data-background="simple_crossroads"/);vm.runInContext("game.position={...game.roomLoot[0].position};render();",context);assert.match(el('nearbyLoot').innerHTML,/Al · Gölge Pelerini/);assert.match(el('miniGrid').innerHTML,/loot/);context.action('loot');assert.ok(el('lootDialog').open);assert.match(el('lootReveal').innerHTML,/Gölge Pelerini/);el('lootDialog').close();
vm.runInContext("game.roomId='seal_room';render();",context);el('sealButton').listeners.click();assert.ok(el('sealDialog').open);assert.match(el('riddleOptions').innerHTML,/data-answer/);assert.ok(el('riddleQuestion').textContent.length>20);el('riddleHintButton').listeners.click();assert.equal(el('riddleHint').hidden,false);el('sealDialog').close();
vm.runInContext("game.roomId='barracks';game.random=()=>.99;game.engage();game.combat.phase='enemy';game.hp=1;game.enemyTurn();record();",context);assert.ok(el('gameShell').classList.contains('hit'));assert.ok(el('deathDialog').open);assert.ok(context.document.body.classList.contains('dead-screen'));const oldRiddle=vm.runInContext('game.riddle.id',context);el('deathRestart').listeners.click();assert.equal(vm.runInContext('game.dead',context),false);assert.equal(vm.runInContext('game.hp',context),24);assert.notEqual(vm.runInContext('game.riddle.id',context),oldRiddle);assert.equal(context.document.body.classList.contains('dead-screen'),false);
console.log('Passed: direct room choices, inspect/read interactions, class stealth probabilities, four stable per-run riddles, crafting, preparation initiative, 3-AP combat and UI loot/riddle/damage/death/restart.');
