const {collectRoom,takeWeaponAt}=require('./test-loot-helpers');
const assert=require('node:assert/strict'),fs=require('node:fs');const {DungeonExplorer}=require('./game-engine');const read=p=>JSON.parse(fs.readFileSync(p));const map=read('dungeon_map.json'),rules=read('game_rules.json'),bestiary=read('bestiary.json'),loot=read('loot.json');
const make=(cls='Fighter')=>new DungeonExplorer(map,rules,cls,'Test',{bestiary,loot,random:()=>.99});
function walkToDoor(g,door){const target=door.position||g.spawnPosition(door),key=p=>p.x+','+p.y,queue=[[g.position,[]]],seen=new Set([key(g.position)]);let path;
  while(queue.length){const [p,route]=queue.shift();if(g.distance(p,target)<=1){path=route;break;}for(const [d,v] of [[0,[0,-1]],[1,[1,0]],[2,[0,1]],[3,[-1,0]]]){const q={x:p.x+v[0],y:p.y+v[1]};if(g.walkable(q)&&!seen.has(key(q))){seen.add(key(q));queue.push([q,[...route,d]]);}}}
  assert.ok(path,'Kapı yolu bulunmalı: '+g.roomId+' → '+door.target);for(const d of path){assert.ok(g.move(d));assert.equal(g.combat,null);}assert.ok(g.distance(g.position,target)<=1);
}
for(const cls of ['Fighter','Mage','Rogue']){const g=make(cls);const visit=target=>{if(g.currentEnemies.length)g.sneak();const door=g.doors().find(d=>d.target===target);walkToDoor(g,door);assert.ok(g.goDoor(door.id));};g.prepare();visit('hall');visit('troll_hall');visit('seal_room');g.answerRiddle(g.riddle.answer);visit('guardian');visit('vault');walkToDoor(g,{position:g.availableLoot.find(e=>e.id==='seal_stone').position});g.collectLoot();assert.ok(g.hasStone);visit('guardian');visit('seal_room');visit('troll_hall');visit('hall');visit('entrance');assert.ok(g.completed);}
const movement=make();const start={...movement.position};movement.move('forward',3);assert.equal(start.y-movement.position.y,3);const wall={...movement.position};movement.move('forward',3);assert.deepEqual(movement.position,wall);movement.move('back');assert.equal(movement.position.y,wall.y+1);movement.turnFacing(1);assert.equal(movement.facing,1);
const noisy=make();noisy.roomId='troll_hall';const mob=noisy.currentEnemies[0];noisy.position={x:mob.position.x,y:mob.position.y+4};noisy.facing=0;noisy.move('forward',3);assert.ok(noisy.combat);assert.equal(noisy.position.y,mob.position.y+1);
const quiet=make();quiet.roomId='troll_hall';quiet.position={x:mob.position.x,y:mob.position.y+4};quiet.move(0);assert.equal(quiet.combat,null);quiet.move(0);assert.equal(quiet.combat,null);quiet.prepare();quiet.move(0);assert.equal(quiet.combat,null);assert.equal(quiet.visibleEnemies.length,1);quiet.engage();assert.ok(quiet.combat.preparedAtStart);
const gear=make();gear.roomId='armory';collectRoom(gear);assert.equal(Object.keys(gear.inventory).filter(id=>gear.items.get(id).slot==='weapon').length,1);assert.ok(gear.availableWeapons.includes('war_hammer'));const starter=gear.equipment.weapon;assert.ok(takeWeaponAt(gear,'war_hammer'));assert.equal(gear.inventory[starter],undefined);assert.ok(gear.availableWeapons.includes(starter));assert.equal(gear.attackCost,2);gear.roomId='troll_hall';gear.position=gear.spawnPosition();gear.engage();gear.combat.phase='player';gear.target.hp=200;const before=gear.target.hp;gear.attack();assert.equal(gear.combat.ap,1);assert.ok(before-gear.target.hp>=27);const hp=gear.target.hp;gear.attack();assert.equal(gear.combat.ap,1);assert.equal(gear.target.hp,hp);gear.endTurn();gear.enemyTurn();gear.random=()=>0;gear.attack();assert.equal(gear.combat.ap,1);assert.equal(gear.target.hp,hp);
gear.combat=null;gear.roomId='armory';assert.ok(takeWeaponAt(gear,'ash_spear'));assert.equal(gear.attackCost,1);assert.ok(gear.availableWeapons.includes('war_hammer'));assert.equal(Object.keys(gear.inventory).filter(id=>gear.items.get(id).slot==='weapon').length,1);assert.ok(takeWeaponAt(gear,starter));assert.equal(gear.equipment.weapon,starter);
const mage=make('Mage');mage.roomId='armory';collectRoom(mage);assert.equal(takeWeaponAt(mage,'war_hammer'),false);assert.ok(takeWeaponAt(mage,'rune_staff'));assert.equal(Object.keys(mage.inventory).filter(id=>mage.items.get(id).slot==='weapon').length,1);
console.log('Passed: all classes complete actual grid routes and return quest; walls, facing, 1/3 steps, noise/initiative; single-weapon swapping and ground persistence; hammer 2 AP, high damage, misses and insufficient AP.');
module.exports={walkToDoor};
