const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {DungeonExplorer}=require('./game-engine');const read=p=>JSON.parse(fs.readFileSync(p));const map=read('dungeon_map.json'),rules=read('game_rules.json'),bestiary=read('bestiary.json'),loot=read('loot.json');
const make=(cls='Fighter',random=()=>.5,extra={})=>new DungeonExplorer(map,rules,cls,'Test',{fixedSpawns:true,bestiary,loot,random,...extra});
const g=make();assert.equal(g.room.name,'Doğu Kapısı Hücreleri');assert.equal(g.hp,30);assert.equal(g.potions,0);assert.equal(typeof g.move,'function');g.inspect();assert.ok(g.inspected.has(map.start));assert.ok(g.readEntry('text_0').text.length>100);g.hp=10;g.interact('water');assert.equal(g.hp,14);g.interact('water');assert.equal(g.hp,14);
const door=g.doors()[0];g.position=g.spawnPosition(door);assert.ok(g.goDoor(door.id));assert.equal(typeof g.advanceCorridor,'undefined');assert.equal(g.canAct(),true);assert.equal(g.roomId,'hall');assert.equal(g.combat,null);
g.roomId='barracks';g.bypassed=false;assert.equal(g.goDoor(g.doors()[0].id),false);g.prepare();assert.equal(g.combat,null);g.engage();assert.ok(g.combat);assert.equal(g.combat.preparedAtStart,true);g.combat.phase='player';g.target.hp=100;g.target.maxHp=100;g.attack();g.attack();g.attack();assert.equal(g.combat.phase,'enemy');g.enemyTurn();assert.equal(g.combat.ap,3);assert.ok(g.hp<g.maxHp);
function sneakRate(cls){let wins=0;for(let die=1;die<=20;die++){const x=make(cls);x.roomId='barracks';x.random=()=> (die-.5)/20;x.sneak();if(x.bypassed)wins++;}return wins;}
assert.equal(sneakRate('Fighter'),3);assert.equal(sneakRate('Rogue'),18);
for(let i=0;i<4;i++){const x=make('Rogue',()=> (i+.1)/4);assert.equal(x.riddle.id,map.riddles[i].id);x.roomId='seal_room';assert.equal(x.answerRiddle((x.riddle.answer+1)%4),false);assert.equal(x.sealSolved,false);assert.ok(x.alarm>0);assert.equal(x.answerRiddle(x.riddle.answer),true);assert.equal(x.sealSolved,true);}
const previous=make().riddle.id;assert.notEqual(make('Fighter',()=>.5,{previousRiddleId:previous}).riddle.id,previous);
const mage=make('Mage',()=>.9);mage.roomId='rune_hall';mage.inspect();mage.interact('brew');assert.equal(mage.potions,1);mage.interact('brew');assert.equal(mage.potions,1);mage.position=mage.spawnPosition(mage.doors().find(d=>d.target==='archive'));mage.goDoor(mage.doors().find(d=>d.target==='archive').id);assert.equal(mage.focus,5);mage.inspect();assert.ok(mage.finalAdvantage);mage.focus=4;mage.interact('study');assert.equal(mage.focus,6);
const elements=new Map(),timers=new Map();let id=0;
function classes(){const values=new Set();return {add(v){values.add(v);},remove(v){values.delete(v);},toggle(v,on){if(on)values.add(v);else values.delete(v);},contains(v){return values.has(v);}};}
function el(name){if(!elements.has(name))elements.set(name,{textContent:'',innerHTML:'',value:'',hidden:false,disabled:false,open:false,style:{},classList:classes(),attributes:{},listeners:{},setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,v){this.listeners[k]=v;},querySelectorAll(){return [];},showModal(){this.open=true;},close(){this.open=false;},setCustomValidity(){},reportValidity(){}});return elements.get(name);}
const storage=new Map();const context={CHARACTER_NAMES:require('./character-name-data'),MAP:map,RULES:rules,BESTIARY:bestiary,LOOT:loot,ASSETS:Object.fromEntries([...map.rooms.map(r=>r.art),...map.rooms.map(r=>r.enemy_art).filter(Boolean),'simple_vault_empty'].map(k=>[k,'test:'+k])),document:{body:{classList:classes()},getElementById:el,addEventListener(){},querySelector(){return [...elements.values()].find(e=>e.open)||null;},querySelectorAll(){return [];}},localStorage:{getItem(k){return storage.get(k)||null;},setItem(k,v){storage.set(k,v);}},setTimeout(fn){timers.set(++id,fn);return id;},clearTimeout(key){timers.delete(key);}};vm.createContext(context);vm.runInContext(fs.readFileSync('game-engine.js','utf8'),context);vm.runInContext(fs.readFileSync('game-ui.js','utf8'),context);
assert.ok(el('characterDialog').open);assert.match(el('creationPortrait').innerHTML,/data-class="Fighter"/);for(const cls of ['Mage','Rogue','Fighter']){el('classInput').value=cls;el('classInput').listeners.change();assert.ok(el('creationPortrait').innerHTML.includes('data-class="'+cls+'"'));assert.equal(el('previewClassName').textContent,cls);}
const physicalIcons=['battle_axe','war_hammer','iron_mace','ash_spear','starter_rogue','iron_sword'].map(id=>{const svg=context.characterPortrait('Fighter',{id},true);assert.ok(svg.includes('data-weapon="'+id+'"'));return svg;});assert.equal(new Set(physicalIcons).size,physicalIcons.length);assert.ok(!context.characterPortrait('Fighter',{id:'battle_axe'},false).includes('data-prepared'));
for(const [id,color] of Object.entries({fireball_staff:'#ffd25b',lightning_staff:'#66baff',ice_staff:'#9ae6ed',rune_staff:'#74d998',starter_mage:'#c29aff'})){const svg=context.characterPortrait('Mage',{id,staff:id!=='starter_mage'},true);assert.ok(svg.includes('data-magic-color="'+color+'"'));assert.ok(svg.includes('data-weapon="'+id+'"'));}assert.ok(!context.characterPortrait('Rogue',{id:'fireball_staff',staff:true},true).includes('data-prepared="magic"'));
for(const kind of ['skeleton','spider','troll'])assert.ok(context.mapEnemyIcon(kind).includes('data-map-enemy="'+kind+'"'));assert.match(el('miniGrid').innerHTML,/data-map-item="old_map"/);
const generatedName=el('nameInput').value;assert.ok(generatedName.length>0&&generatedName.length<=36);assert.match(el('nameSuggestions').innerHTML,/data-suggested-name/);el('rerollName').listeners.click();assert.notEqual(el('nameInput').value,generatedName);el('nameInput').value='Mira';el('classInput').value='Rogue';el('characterForm').listeners.submit({preventDefault(){}});assert.ok(el('questDialog').open);el('acceptQuest').listeners.click();assert.match(el('scene').innerHTML,/data-background="simple_prison"/);assert.ok(!el('explorationActions').innerHTML.includes('adım'));assert.ok(el('doorChoices').hidden);assert.match(el('miniControls').innerHTML,/3 adım/);assert.match(el('miniGrid').innerHTML,/map-cell/);const navEvent=(key,extra={})=>({key,target:{closest(){return null;}},preventDefault(){},...extra});const startPosition=vm.runInContext('JSON.stringify(game.position)',context);context.handleNavigationKey(navEvent('a'));assert.equal(vm.runInContext('game.facing',context),3);assert.equal(vm.runInContext('JSON.stringify(game.position)',context),startPosition);context.handleNavigationKey(navEvent('a'));assert.notEqual(vm.runInContext('JSON.stringify(game.position)',context),startPosition);context.handleNavigationKey(navEvent('d'));assert.equal(vm.runInContext('game.facing',context),1);context.handleNavigationKey(navEvent('d'));assert.equal(vm.runInContext('JSON.stringify(game.position)',context),startPosition);context.handleNavigationKey(navEvent('w'));assert.equal(vm.runInContext('game.facing',context),0);context.handleNavigationKey(navEvent('w'));assert.notEqual(vm.runInContext('JSON.stringify(game.position)',context),startPosition);context.handleNavigationKey(navEvent('s'));assert.equal(vm.runInContext('game.facing',context),2);context.handleNavigationKey(navEvent('s'));assert.equal(vm.runInContext('JSON.stringify(game.position)',context),startPosition);context.handleNavigationKey(navEvent('w'));const beforeTyping=vm.runInContext('game.turn',context);context.handleNavigationKey(navEvent('w',{target:{closest(){return {};}}}));context.handleNavigationKey(navEvent('w',{ctrlKey:true}));context.handleNavigationKey(navEvent('w',{repeat:true}));assert.equal(vm.runInContext('game.turn',context),beforeTyping);el('historyDialog').showModal();context.handleNavigationKey(navEvent('w'));assert.equal(vm.runInContext('game.turn',context),beforeTyping);el('historyDialog').close();
assert.ok(!el('explorationActions').innerHTML.includes('Odayı incele'));
vm.runInContext("game.position=game.spawnPosition(game.doors()[0]);game.goDoor(game.doors()[0].id);render();",context);assert.match(el('scene').innerHTML,/data-background="simple_crossroads"/);vm.runInContext("game.position={...game.roomLoot[0].position};game.inspect();render();",context);assert.match(el('nearbyLoot').innerHTML,/Al · Rivendell Pelerini/);assert.match(el('miniGrid').innerHTML,/loot/);context.action('loot');assert.ok(el('lootDialog').open);assert.match(el('lootReveal').innerHTML,/Rivendell Pelerini/);el('lootDialog').close();
vm.runInContext("game.roomId='seal_room';render();",context);vm.runInContext("game.position=game.spawnPosition(game.doors().find(d=>d.connection.gate!=='seal_puzzle'));render();",context);assert.equal(el('sealButton').hidden,true);context.openRiddle();assert.equal(el('sealDialog').open,false);const puzzleDoor=vm.runInContext("game.doors().find(d=>d.connection.gate==='seal_puzzle').id",context);vm.runInContext("game.position=game.spawnPosition(game.doors().find(d=>d.connection.gate==='seal_puzzle'));",context);context.render();assert.equal(el('sealButton').hidden,false);context.openMapDoor(puzzleDoor);assert.ok(el('sealDialog').open);el('sealDialog').close();el('sealButton').listeners.click();assert.ok(el('sealDialog').open);assert.match(el('riddleOptions').innerHTML,/data-answer/);assert.ok(el('riddleQuestion').textContent.length>20);el('riddleHintButton').listeners.click();assert.equal(el('riddleHint').hidden,false);el('sealDialog').close();
// Keep the sight-line fixture clear of pillars; production spawns are randomized.
vm.runInContext("game.enemies.find(e=>e.roomId==='troll_hall').position={x:27,y:17};",context);
vm.runInContext("game.roomId='hall';const arrivalDoor=game.doors().find(d=>d.target==='troll_hall');game.position=game.spawnPosition(arrivalDoor);game.goDoor(arrivalDoor.id);render();",context);assert.ok(el('encounterDialog').open);assert.equal(el('encounterTitle').textContent,'Yalnız değilsin…');assert.match(el('encounterText').textContent,/hırıltı/);assert.equal(el('encounterText').hidden,false);assert.equal(el('encounterScene').hidden,true);assert.equal(el('encounterImage').hidden,true);assert.ok(!el('encounterChoices').innerHTML.includes('noticeAttack'));el('noticeContinue').onclick();
vm.runInContext("game.roomId='troll_hall';game.random=()=>.99;game.position={x:game.currentEnemies[0].position.x,y:game.currentEnemies[0].position.y+3};game.facing=0;game.torchLit=true;game.checkEncounter();render();",context);assert.ok(el('encounterDialog').open);assert.equal(el('encounterImage').hidden,false);assert.equal(el('encounterText').hidden,true);assert.match(el('encounterTitle').textContent,/tam karşında/);assert.equal(el('encounterImage').src,'test:boss_lava_hall_enemy');el('noticeSneak').onclick();assert.equal(el('encounterDialog').open,false);assert.equal(vm.runInContext('game.torchLit',context),false);assert.equal(vm.runInContext('game.bypassed',context),true);
vm.runInContext("game.bypassed=false;game.torchLit=true;game.noticedEnemies.clear();game.checkEncounter();render();",context);el('noticeAttack').onclick();assert.ok(vm.runInContext('game.combat',context));assert.equal(el('encounterDialog').open,false);assert.equal(el('battleConsole').hidden,false);assert.match(el('battleLog').innerHTML,/savaş başladı/);vm.runInContext('game.combat=null;render();',context);assert.equal(el('battleConsole').hidden,true);
vm.runInContext("game.roomId='troll_hall';game.bypassed=false;game.torchLit=false;game.random=()=>0;game.sneak();game.combat.phase='enemy';render();",context);assert.ok(el('resultDialog').open);assert.match(el('resultText').textContent,/Zırhın bazalta/);assert.equal(vm.runInContext('enemyTimer',context),null,'Sonuç penceresi açıkken düşman turu beklemeli');el('resultContinue').listeners.click();assert.equal(el('resultDialog').open,false);assert.ok(vm.runInContext('enemyTimer',context));vm.runInContext('game.combat=null;game.resultNotice=null;render();',context);
vm.runInContext("game.roomId='barracks';game.random=()=>.99;game.engage();game.combat.phase='enemy';game.hp=1;game.enemyTurn();record();",context);assert.ok(el('gameShell').classList.contains('hit'));assert.ok(el('deathDialog').open);assert.ok(context.document.body.classList.contains('dead-screen'));const oldRiddle=vm.runInContext('game.riddle.id',context);el('deathRestart').listeners.click();assert.equal(vm.runInContext('game.dead',context),false);assert.equal(vm.runInContext('game.hp',context),24);assert.notEqual(vm.runInContext('game.riddle.id',context),oldRiddle);assert.equal(context.document.body.classList.contains('dead-screen'),false);
console.log('Passed: direct room choices, inspect/read interactions, class stealth probabilities, four stable per-run riddles, crafting, preparation initiative, 3-AP combat and UI loot/riddle/damage/death/restart.');
